### Retrieve all tasks.
GET http://localhost:3000/tasks


### Retrieve a single task by ID.
GET http://localhost:3000/tasks/45

### Create a new task.
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "Work",
    "categoryId": "12345",
    "description": "This is a task for work"
}


###  Delete a task by ID.
DELETE http://localhost:3000/tasks/35343


### Retrieve all categories.
GET http://localhost:3000/categories

### Create a new category.
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "The gym"
}