### Retrieve all tasks.
GET http://localhost:3000/tasks


### Retrieve a single task by ID.
GET http://localhost:3000/tasks/cb3d530b-69b9-43db-974e-120fc19ff699

### Create a new task.
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "Doexercises",
    "categoryId": "c69da9e9-20b5-4bde-9606-109c715674b7",
    "description": "This is a task for work"
}


###  Delete a task by ID.
DELETE http://localhost:3000/tasks/cb3d530b-69b9-43db-974e-120fc19ff699


### Retrieve all categories.
GET http://localhost:3000/categories

### Create a new category.
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Personal"
}